spring:
  # H2 in-memory database for tests
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  # Disable cloud config
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

# Disable Eureka
eureka:
  client:
    enabled: false

