jenkins:
  systemMessage: "E-commerce Microservices CI/CD - Configured with JCasC"
  numExecutors: 4
  mode: NORMAL
  scmCheckoutRetryCount: 3
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_USER}"
          password: "${JENKINS_ADMIN_PASSWORD}"
          
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_ADMIN_USER}"
        - "Overall/Read:authenticated"
        
  clouds:
    - kubernetes:
        name: "local-k8s"
        serverUrl: "https://kubernetes.default.svc"
        skipTlsVerify: true
        namespace: "jenkins"
        jenkinsUrl: "http://jenkins:8080"
        connectTimeout: 0
        readTimeout: 0
        containerCapStr: 100
        maxRequestsPerHostStr: 64
        retentionTimeout: 5
        
  remotingSecurity:
    enabled: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-token"
              username: "ChrisBotina7823"
              password: "${GITHUB_TOKEN}"
              description: "GitHub Personal Access Token"
              
          - usernamePassword:
              scope: GLOBAL
              id: "docker-registry"
              username: "${DOCKER_REGISTRY_USER}"
              password: "${DOCKER_REGISTRY_PASS}"
              description: "Docker Registry Credentials"
            
          - file:
              scope: GLOBAL
              id: "kubeconfig"
              fileName: "kubeconfig"
              secretBytes: ${KUBECONFIG_BASE64}
              description: "Local Kubernetes Cluster Config"
              
          - usernamePassword:
              scope: GLOBAL
              id: "sonarqube-admin"
              username: "admin"
              password: "${SONAR_ADMIN_PASSWORD}"
              description: "SonarQube Admin Credentials"

unclassified:
  location:
    url: "${JENKINS_URL}"
    
  gitHubPluginConfig:
    configs:
      - name: "GitHub"
        credentialsId: "github-token"
        manageHooks: true
        
  timestamper:
    allPipelines: true
    
  sonarGlobalConfiguration:
    installations:
      - name: "SonarQube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonarqube-admin"
        
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver

jobs:
  - script: >
      multibranchPipelineJob('ecommerce-microservices') {
        branchSources {
          github {
            id('ecommerce-repo')
            repoOwner('ChrisBotina7823')
            repository('proyecto-final-ingesoft5-services')
            scanCredentialsId('github-token')
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(5)
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('1m')
          }
        }
      }
