jenkins:
  systemMessage: "E-commerce Microservices CI/CD - Configured with JCasC"
  numExecutors: 4
  mode: NORMAL
  scmCheckoutRetryCount: 3
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_USER}"
          password: "${JENKINS_ADMIN_PASSWORD}"
          
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_ADMIN_USER}"
        - "Overall/Read:authenticated"
        
  clouds:
    - kubernetes:
        name: "local-k8s"
        serverUrl: "https://kubernetes.default.svc"
        skipTlsVerify: true
        namespace: "jenkins"
        jenkinsUrl: "http://jenkins:8080"
        connectTimeout: 0
        readTimeout: 0
        containerCapStr: 100
        maxRequestsPerHostStr: 64
        retentionTimeout: 5
        
  remotingSecurity:
    enabled: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-token"
              username: "ChrisBotina7823"
              password: "${GITHUB_TOKEN}"
              description: "GitHub Personal Access Token"
              
          - usernamePassword:
              scope: GLOBAL
              id: "docker-registry"
              username: "${DOCKER_REGISTRY_USER}"
              password: "${DOCKER_REGISTRY_PASS}"
              description: "Docker Registry Credentials"
            
          - file:
              scope: GLOBAL
              id: "kubeconfig"
              fileName: "kubeconfig"
              secretBytes: ${file:/var/jenkins_home/kubeconfig.base64}
              description: "Kubernetes Cluster Config"
              
          - usernamePassword:
              scope: GLOBAL
              id: "sonarqube-admin"
              username: "admin"
              password: "${SONAR_ADMIN_PASSWORD}"
              description: "SonarQube Admin Credentials"
              
          - string:
              scope: GLOBAL
              id: "slack-token"
              secret: "${SLACK_TOKEN}"
              description: "Slack Bot Token"
              
          - usernamePassword:
              scope: GLOBAL
              id: "smtp-credentials"
              username: "${SMTP_USER}"
              password: "${SMTP_PASSWORD}"
              description: "SMTP Email Credentials"

unclassified:
  location:
    url: "${JENKINS_URL}"
    
  gitHubPluginConfig:
    configs:
      - name: "GitHub"
        credentialsId: "github-token"
        manageHooks: true
        
  timestamper:
    allPipelines: true
    
  sonarGlobalConfiguration:
    installations:
      - name: "SonarQube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonarqube-admin"
        
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
    
  slackNotifier:
    teamDomain: "${SLACK_WORKSPACE}"
    tokenCredentialId: "slack-token"
    room: "#deployments"
    sendAsText: false
    
  mailer:
    smtpHost: "${SMTP_HOST:-smtp.gmail.com}"
    smtpPort: "${SMTP_PORT:-587}"
    useSsl: true
    charset: "UTF-8"
    authentication:
      username: "${SMTP_USER}"
      password: "${SMTP_PASSWORD}"
    
  extendedEmailPublisher:
    defaultContentType: "text/html"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS"
    defaultBody: |
      <h2>Build $BUILD_STATUS</h2>
      <p><strong>Project:</strong> $PROJECT_NAME</p>
      <p><strong>Build Number:</strong> $BUILD_NUMBER</p>
      <p><strong>Build URL:</strong> <a href="$BUILD_URL">$BUILD_URL</a></p>
    smtpHost: "${SMTP_HOST:-smtp.gmail.com}"
    smtpPort: "${SMTP_PORT:-587}"
    useSsl: true
    smtpAuthUsername: "${SMTP_USER}"
    smtpAuthPassword: "${SMTP_PASSWORD}"

jobs:
  - script: >
      multibranchPipelineJob('ecommerce-microservices') {
        branchSources {
          github {
            id('ecommerce-repo')
            repoOwner('ChrisBotina7823')
            repository('proyecto-final-ingesoft5-services')
            scanCredentialsId('github-token')
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(5)
          }
        }
        triggers {
          periodicFolderTrigger {
            interval('1m')
          }
        }
      }
