jenkins:
  systemMessage: "E-commerce Microservices CI/CD - Configured with JCasC"
  numExecutors: 4
  mode: NORMAL
  scmCheckoutRetryCount: 3
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_USER:-admin}"
          password: "${JENKINS_ADMIN_PASSWORD:-admin123}"
          
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_ADMIN_USER:-admin}"
        - "Overall/Read:authenticated"
        
  clouds:
    - kubernetes:
        name: "local-k8s"
        serverUrl: "https://kubernetes.default.svc"
        skipTlsVerify: true
        namespace: "jenkins"
        jenkinsUrl: "http://jenkins:8080"
        connectTimeout: 0
        readTimeout: 0
        containerCapStr: 100
        maxRequestsPerHostStr: 64
        retentionTimeout: 5
        
  remotingSecurity:
    enabled: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "github-token"
              secret: "${GITHUB_TOKEN:-changeme}"
              description: "GitHub Personal Access Token"
              
          - usernamePassword:
              scope: GLOBAL
              id: "docker-registry"
              username: "${DOCKER_REGISTRY_USER:-admin}"
              password: "${DOCKER_REGISTRY_PASS:-admin}"
              description: "Docker Registry Credentials"
              
          - file:
              scope: GLOBAL
              id: "kubeconfig-local"
              fileName: "kubeconfig"
              secretBytes: "${KUBECONFIG_CONTENT_BASE64}"
              description: "Local Kubernetes Cluster Config"

unclassified:
  location:
    url: "http://localhost:8090/"
    
  gitHubPluginConfig:
    configs:
      - name: "GitHub"
        credentialsId: "github-token"
        
  timestamper:
    allPipelines: true
